#!/usr/bin/env python
# -*- coding: ANSI_X3.4-1968 -*-
# generated by wxGlade 0.3.5.1 on Sun May 29 16:40:22 2005

import wx
import sys
from wxMainFrame import wxMainFrame

class CDRipper(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        device = "/dev/cdrom"
        if len(sys.argv) > 1:
            device = sys.argv[1]
        frame_main = wxMainFrame(None, -1, "", device=device)
        self.SetTopWindow(frame_main)
        frame_main.Show()
        return 1

# end of class CDRipper

if __name__ == "__main__":
    CDRipper = CDRipper(0)
    CDRipper.MainLoop()
