# -*- coding: ANSI_X3.4-1968 -*-
# generated by wxGlade 0.3.5.1 on Sun May 29 16:39:49 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class wxMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxMainFrame.__set_properties
        self.SetTitle("MetaRipper - CDRipper")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxMainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class wxMainFrame


